### ISSUE TITLE
URLのユーザーID表示形式を変更する

### ISSUE THREAD

**Issue by yanokohei** [yanokohei/goenbako#65]
ユーザーページなどのURLの識別IDをTwitterのIDに変更し正常に動作すること。

意図したURLに対してページを表示し、URLにアクセスすることは出来るようになった。
ユーザーの情報も渡っているが
mounted時のリスト表示のリクエストがエラーになってしまう。

## ブラウザのコンソール
![image](https://user-images.githubusercontent.com/78721963/144312133-d4a00c7d-a231-4c69-b82d-462588eacb68.png)
POSTの部分に関してはブラウザ側でレター作成をした結果。

## ターミナル・サーバーログ
```
Started GET "/users/T_witter_id" for 127.0.0.1 at 2021-12-02 05:55:45 +0900
Processing by HomeController#index as HTML
  Parameters: {"path"=>"users/T_witter_id"}
  Rendering home/index.html.erb within layouts/application
  Rendered home/index.html.erb within layouts/application (Duration: 0.0ms | Allocations: 4)
Completed 200 OK in 9ms (Views: 8.5ms | ActiveRecord: 0.0ms | Allocations: 5184)


Started GET "/api/users/T_witter_id/received_letters" for 127.0.0.1 at 2021-12-02 05:55:45 +0900
Started GET "/api/users/T_witter_id" for 127.0.0.1 at 2021-12-02 05:55:45 +0900
Started GET "/api/users/T_witter_id/sent_letters" for 127.0.0.1 at 2021-12-02 05:55:45 +0900
Processing by Api::UsersController#received_letters as HTML
  Parameters: {"twitter_id"=>"T_witter_id"}
  User Load (0.8ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", nil], ["LIMIT", 1]]
  ↳ app/controllers/api/users_controller.rb:17:in `received_letters'
Completed 404 Not Found in 4ms (ActiveRecord: 1.1ms | Allocations: 4499)



ActiveRecord::RecordNotFound - Couldn't find User with 'id'={:twitter_id=>"T_witter_id"}:
  app/controllers/api/users_controller.rb:17:in `received_letters'

Processing by Api::UsersController#show as HTML
  Parameters: {"twitter_id"=>"T_witter_id"}
Processing by Api::UsersController#sent_letters as HTML
  Parameters: {"twitter_id"=>"T_witter_id"}
  User Load (1.0ms)  SELECT "users".* FROM "users" WHERE "users"."twitter_id" = $1 LIMIT $2  [["twitter_id", "T_witter_id"], ["LIMIT", 1]]
  ↳ app/controllers/api/users_controller.rb:30:in `show'
Completed 200 OK in 4ms (Views: 0.3ms | ActiveRecord: 1.2ms | Allocations: 4749)


  User Load (1.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", nil], ["LIMIT", 1]]
  ↳ app/controllers/api/users_controller.rb:4:in `sent_letters'
Completed 404 Not Found in 4ms (ActiveRecord: 1.3ms | Allocations: 5608)



ActiveRecord::RecordNotFound - Couldn't find User with 'id'={:twitter_id=>"T_witter_id"}:
  app/controllers/api/users_controller.rb:4:in `sent_letters'
```

#### （ブラウザ側でレター作成をした場合のログ）
```
Started POST "/api/letters" for 127.0.0.1 at 2021-12-02 05:57:01 +0900
Processing by Api::LettersController#create as HTML
  Parameters: {"letter"=>{"sender_id"=>1, "past"=>"AA", "current"=>"BB", "future"=>"CC", "expect"=>"DD", "message"=>"EE"}}
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/api/letters_controller.rb:10:in `create'
   (0.1ms)  BEGIN
  ↳ app/controllers/api/letters_controller.rb:11:in `create'
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/api/letters_controller.rb:11:in `create'
   (0.2ms)  ROLLBACK
  ↳ app/controllers/api/letters_controller.rb:11:in `create'
Completed 400 Bad Request in 6ms (Views: 0.1ms | ActiveRecord: 0.8ms | Allocations: 5636)
```

#### app/javascript/router/index.js　（ルーター）

```javascript
import Vue from "vue";
import Router from "vue-router";
import TopIndex from "../pages/top/index";
import UserIndex from "../pages/user/index";
import MypageIndex from "../pages/mypage/index";

Vue.use(Router)

const router = new Router({
  mode: "history",
  routes: [
    {
      path: "/",
      component: TopIndex,
      name: "TopIndex",
    },
    {
      path: "/mypage",
      component: MypageIndex,
      name: "MypageIndex",
    },
    {
      path: "/users/:twitter_id",
      component: UserIndex,
      name: "UserIndex",
    },
  ],
})

export default router
```

#### app/javascript/pages/user/index.vue　（ユーザーページ）
```javascript
<template>
  <v-container>
    {{this.user}}
    <v-row
      class="ma-8"
      justify="center"
    >
      <UserProfileCard
        :user="user"
      />
    </v-row>
省略
  </v-container>
</template>

<script>
import axios from "axios";
import { mapGetters } from "vuex";
import UserProfileCard from "../components/UserProfileCard";
import NotSendLetter from "../components/NotSendLetter";
import CreateLetterModal from "../components/CreateLetterModal";
import DoneSendLetter from "../components/DoneSendLetter";
import LetterListTab from '../components/LetterListTab';

export default {
  name: "UserIndex",
  components: {
    UserProfileCard,
    CreateLetterModal,
    NotSendLetter,
    DoneSendLetter,
    LetterListTab,
  },

  data() {
    return {
      user: {},
      receivedLetters: [],
      sentLetters: [],
      isVisibleCreateLetterModal: false,
    };
  },
  mounted() {
    this.fetchUser()
    this.fetchReceivedLetters()
    this.fetchSentLetters()
  },
  computed: {
    ...mapGetters("users", ["currentUser"]),
    currentPath() {
      return this.$route.path
    }
  },
  methods: {
    async fetchUser() {
      await axios.get(`/api/users/${this.$route.params.twitter_id}`)
      .then((res) => {
        this.user = res.data
      })
    },
    async fetchReceivedLetters() {
      await axios.get(`/api/users/${this.$route.params.twitter_id}/received_letters`)
        .then((res) => {
          this.receivedLetters = res.data
        })
    },
    async fetchSentLetters() {
      await axios.get(`/api/users/${this.$route.params.twitter_id}/sent_letters`)
        .then((res) => {
          this.sentLetters = res.data
        })
    },
    openCreateLetterModal() {
      this.isVisibleCreateLetterModal = true;
    },
    handleCloseCreateLetterModal() {
      this.isVisibleCreateLetterModal = false;
    }
  },
  watch: {
    currentPath: function() {
      this.fetchUser()
      this.fetchReceivedLetters()
      this.fetchSentLetters()
    }
  },
};
</script>
```

routes.rb
```ruby
    resources :users, param: :twitter_id, only: %i[index edit update show destroy] do
      collection do
        get 'me'
      end
      member do
        get 'sent_letters'
        get 'received_letters'
      end
    end
```

実行
```
$ rails routes
```
結果
```ruby
                               Prefix Verb   URI Pattern                                                                              Controller#Action
                                 root GET    /                                                                                        home#index
                               mypage GET    /mypage(.:format)                                                                        home#index
                   api_oauth_callback POST   /api/oauth/callback(.:format)                                                            api/oauths#callback
                                      GET    /api/oauth/callback(.:format)                                                            api/oauths#callback
                 api_auth_at_provider GET    /api/oauth/:provider(.:format)                                                           api/oauths#oauth
                           api_logout DELETE /api/logout(.:format)                                                                    api/user_sessions#destroy
                         me_api_users GET    /api/users/me(.:format)                                                                  api/users#me
                sent_letters_api_user GET    /api/users/:uid/sent_letters(.:format)                                                   api/users#sent_letters
            received_letters_api_user GET    /api/users/:uid/received_letters(.:format)                                               api/users#received_letters
                            api_users GET    /api/users(.:format)                                                                     api/users#index
                        edit_api_user GET    /api/users/:uid/edit(.:format)                                                           api/users#edit
                             api_user GET    /api/users/:uid(.:format)                                                                api/users#show
                                      PATCH  /api/users/:uid(.:format)                                                                api/users#update
                                      PUT    /api/users/:uid(.:format)                                                                api/users#update
                                      DELETE /api/users/:uid(.:format)                                                                api/users#destroy
                          api_letters GET    /api/letters(.:format)                                                                   api/letters#index
                                      POST   /api/letters(.:format)                                                                   api/letters#create
                       new_api_letter GET    /api/letters/new(.:format)                                                               api/letters#new
                      edit_api_letter GET    /api/letters/:id/edit(.:format)                                                          api/letters#edit
                           api_letter GET    /api/letters/:id(.:format)                                                               api/letters#show
                                      PATCH  /api/letters/:id(.:format)                                                               api/letters#update
                                      PUT    /api/letters/:id(.:format)                                                               api/letters#update
                                      DELETE /api/letters/:id(.:format)                                                               api/letters#destroy
```

api/users/controller
```ruby
  def sent_letters
    user = User.find(twitter_id: params[:twitter_id])
    @sent_letters = user.letters
    sent_letters = @sent_letters.map do |letter|
      {
        letter: letter,
        sender: letter.sender,
        receiver: letter.receiver
      }
    end
    render json: sent_letters
  end

  def received_letters
    user = User.find(twitter_id: params[:twitter_id])
    @received_letters = user.receivers
    received_letters = @received_letters.map do |letter|
      {
        letter: letter,
        sender: letter.sender,
        receiver: letter.receiver
      }
    end
    render json: received_letters
  end

  def show
    @user = User.find_by(twitter_id: params[:twitter_id])
    render json: @user
  end

  def me
    render json: current_user
  end

  def edit; end

  def update; end

  def destroy
    @user = User.find(twitter_id: params[:twitter_id])
    render json: @user
  end
end
```

参考
https://qiita.com/rnitta/items/02aa057ce8b6dd4e8873

**Comment by yanokohei** [comment]
## **find**

特定の”ID”のレコードを１つ探す

```ruby
# 特定の”ID”のレコードを１つ探す
User.find(1)

# カラムを指定してデータを引っ張ってくることは出来ない（idのみ）
ActiveRecord::RecordNotFound: Couldn't find User with 'id'

# 複数のIDを指定することも出来るが見つからないIDがあると以下のエラーを吐く
ActiveRecord::RecordNotFound: Couldn't find all Users with 'id': (1, 3) (found 1 results, but was looking for 2)
```

## **find_by**

指定したカラムが特定の値を持つレコードを１つ探す。

```ruby
# 指定したカラムが特定の値を持つレコードを１つ探す。 
User.find_by(email:"example@exmaple.com")

# 何もヒットしなければ nil を返す
=> nil

# カラム名の指定をしないとエラーになる
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'example' in 'where clause'

# 複数のデータを取得することは出来ない。
SyntaxError: unexpected ')', expecting =>
```

## **find_by!**

find_byを使う際に何も見つからなかった際にnilではなく例外を返したい場合に使う。

```ruby
#　findを使って何もヒットしなかった場合

例外（ActiveRecord::RecordNotFound）が発生する。

#　find_byを使って何もヒットしなかった場合

nilが返る（例外は発生しない）

#　find_byを使っても例外を発生させたい場合

しかし、find_byを使った場合でも例外を発生させたい場合がある。

そんな時にfind_by!を使う。find_byに「!」を付けるだけ
```
